import Images from "./Images";
export const Data = [
  {
    id: 1,
    name: "John Doe",
    age: 30,
    image: Images.Employee1Image,
    department: "Strategic Initiatives",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 25,
    image: Images.Employee2Image,
    department: "Marketing",
  },
  {
    id: 3,
    name: "Michael Johnson",
    age: 35,
    image: Images.Employee3Image,
    department: "Finance",
  },
  {
    id: 4,
    name: "Linda Johnson",
    age: 28,
    image: Images.Employee4Image,
    department: "Finance",
  },
  {
    id: 5,
    name: "Morsal Paiman",
    age: 26,
    image: Images.Employee5Image,
    department: "IT",
  },
  {
    id: 6,
    name: "Yosra Wahedi",
    age: 26,
    image: Images.Employee6Image,
    department: "IT",
  },
  {
    id: 7,
    name: "Samuel lyamah",
    age: 26,
    image: Images.Employee7Image,
    department: "Marketing",
  },
  {
    id: 8,
    name: "Hamid Amini",
    age: 18,
    image: Images.Employee8Image,
    department: "Marketing",
  },
  {
    id: 9,
    name: "Dominick Szoboszlai",
    age: 22,
    image: Images.Employee9Image,
    department: "Creative Services",
  },
  {
    id: 10,
    name: "Nasrin Rahmani",
    age: 24,
    image: Images.Employee10Image,
    department: "Purchasing",
  },
  {
    id: 11,
    name: "Kendal Bardot",
    age: 55,
    image: Images.Employee11Image,
    department: "Asset Managment",
  },
  {
    id: 12,
    name: "Michelle Obama",
    age: 38,
    image: Images.Employee12Image,
    department: "Legal",
  },
  {
    id: 13,
    name: "David Obama",
    age: 32,
    image: Images.Employee13Image,
    department: "Production",
  },
  {
    id: 14,
    name: "Jorge Wilson",
    age: 76,
    image: Images.Employee14Image,
    department: "Engineering",
  },
  {
    id: 15,
    name: "Michelle Taylor",
    age: 53,
    image: Images.Employee15Image,
    department: "law",
  },
  {
    id: 16,
    name: "Dan Campbell",
    age: 78,
    image: Images.Employee16Image,
    department: "Graphic Design",
  },
  {
    id: 17,
    name: "Brian Martin",
    age: 37,
    image: Images.Employee17Image,
    department: "law",
  },
  {
    id: 18,
    name: "Dave Anderson",
    age: 30,
    image: Images.Employee18Image,
    department: "Graphic Design",
  },
];
